export const Role = {
    ROLE_LOGIN_REQUEST: 'ROLE_LOGIN_REQUEST',
    ROLE_LOGIN_SUCCESS: 'ROLE_LOGIN_SUCCESS',
    ROLE_LOGIN_FAIL: 'ROLE_LOGIN_FAIL',
    ROLE_LOGOUT: 'ROLE_LOGOUT',
    SET_CURRENT_ROLE: 'SET_CURRENT_ROLE'
};

export const RoleResetPassword = {
    ROLE_RESET_PASSWORD_REQUEST: 'ROLE_RESET_PASSWORD_REQUEST',
    ROLE_RESET_PASSWORD_SUCCESS: 'ROLE_RESET_PASSWORD_SUCCESS',
    ROLE_RESET_PASSWORD_FAIL: 'ROLE_RESET_PASSWORD_FAIL'
};
